[general]
working_directory = "None"
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 100, lines = 30 }
dynamic_padding = true
decorations = "Full"
opacity = 0.85
title = "Alacritty@CachyOS"
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "MonoLisa", style = "Regular" }
bold = { family = "MonoLisa", style = "Bold" }
italic = { family = "MonoLisa", style = "Italic" }
bold_italic = { family = "MonoLisa", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#212C2A"
foreground = "#F8F8F2"
dim_foreground = "#C6C6C2"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "CellBackground"
cursor = "#70A99F"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#415854"
background = "#8AFF80"

[colors.search.focused_match]
foreground = "#415854"
background = "#FFCA80"

[colors.hints.start]
foreground = "#212C2A"
background = "#FFFF80"

[colors.hints.end]
foreground = "#FFFF80"
background = "#212C2A"

[colors.selection]
text = "CellForeground"
background = "#415854"

[colors.normal]
black = "#212C2A"
red = "#FF9580"
green = "#8AFF80"
yellow = "#FFFF80"
blue = "#9580FF"
magenta = "#FF80BF"
cyan = "#80FFEA"
white = "#F8F8F2"

[colors.bright]
black = "#4C6762"
red = "#FFAA99"
green = "#A2FF99"
yellow = "#FFFF99"
blue = "#AA99FF"
magenta = "#FF99CC"
cyan = "#99FFEE"
white = "#FFFFFF"

[colors.dim]
black = "#1A2322"
red = "#CC7766"
green = "#6ECC66"
yellow = "#CCCC66"
blue = "#7766CC"
magenta = "#CC6699"
cyan = "#66CCBB"
white = "#C6C6C2"

[[colors.indexed_colors]]
index = 16
color = "#FFCA80"

[[colors.indexed_colors]]
index = 17
color = "#E67070"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>	"
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
